[package]
name = "esp-mbedtls-sys"
version = "0.1.0"
edition = "2021"

[build-dependencies]
anyhow = "1.0.68"

[dependencies]

[features]
default = []

# Exactly *one* chip MUST be selected via its feature:
esp32 = []
esp32c3 = []
esp32s2 = []
esp32s3 = []
